apiVersion: v1
kind: Service
metadata:
  name: certificateservice-srv
spec:
  type: NodePort
  selector:
   app: certificateservice
  ports:
    - name: certificateservice
      protocol: TCP
      port: 80
      targetPort: 80
